spring:
    datasource:
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        root: info
        com.huben: debug
    file: log/blog-dev.log
